#functions _ 에러 발생

hello()

def hello():
    print("Hi")

#함수 정의 전 호출이 되었기 때문